### ISSUE TITLE
Installation error: curl: (6) Could not resolve host: raw.githubusercontent.com

### ISSUE THREAD

**Issue by vdbhb59** [hectorm/hblock#50] opened 2020-05-27 17:39 UTC
~$ curl -o /tmp/hblock 'https://raw.githubusercontent.com/hectorm/hblock/v2.1.6/hblock' \
> && echo '9e22c32c8ae4d93df18a41f08d31e8668ef4342fda82ca91ec4aa47f718fdadc  /tmp/hblock' | shasum -c \
> && sudo mv /tmp/hblock /usr/local/bin/hblock \
> && sudo chown root:root /usr/local/bin/hblock \
> && sudo chmod 755 /usr/local/bin/hblock
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:00:14 --:--:--     0curl: (6) Could not resolve host: raw.githubusercontent.com

I tried doing it 4-5 times, different connections, restart, clean installation. Nothing works..

**Comment by hectorm** [comment] 2020-05-27 17:48
You can't resolve `raw.githubusercontent.com`, it seems to be a problem in your network configuration. GitHub is operating normally.

**Comment by vdbhb59** [comment] 2020-05-27 17:57
I tried with different connections, including mobile date and wifi. I am able to open or connect to raw.git normally as well as via terminal. However, with hblock, I am facing this, every few days. Then it works again. I have checked as well on other people's computers and separate connections, they do the same, give error..

**Comment by hectorm** [comment] 2020-05-27 18:11
`raw.githubusercontent.com` is a domain owned by GitHub, I have no control over it. You should contact their support if you confirm that this problem is happening to other people, I can't reproduce it.

Could you tell me your DNS server?

**Comment by vdbhb59** [comment] 2020-05-27 18:18
I have already raised to them as well. 3rd time now. Initially they reverted as hblock issue (project) and not git issue. Now on the 3rd attempt they have just responded that they are checking into it (few more users faced it, but probably some awkward issue)..
My DNS is toggled from: https://blog.uncensoreddns.org/dns-servers/

**Comment by hectorm** [comment] 2020-05-27 18:24
Are the other people using the same DNS servers as you?
Could you confirm if you have the same problem with Cloudflare's or Google's DNS servers as well?

**Comment by vdbhb59** [comment] 2020-05-28 20:58
Couple of them yes, and couple of them other ones. None of us use non-foss dns servers.. So no idea on those 2..

**Comment by vdbhb59** [comment] 2020-06-09 16:44
@hectorm update:
If I try any https other than the source links present in your script, I get curl error, https not allowed..
I have faced this many a times. Even if I use raw github links.
Also, the only way around is to reinstall hblock script from scratch, and after 2 or 3 script runs, it throws the curl https error again.

**Comment by hectorm** [comment] 2020-06-09 17:35
GitHub is working properly and the download of the sources is done through the cURL installed in your system, if any of this is failing it has nothing to do with hBlock.

I'm going to close this issue, because there is nothing I can fix.

**Closed by hectorm** 2020-06-09 17:35 UTC
