### ISSUE TITLE
hBlock host_adblock blocking microsoft

### ISSUE THREAD

**Issue by sh-hi** [hectorm/hblock#163] opened 2024-07-25 13:07 UTC
**Describe the bug:**
new host update blocks microsoft services (skype, onedrive, except ms365)

**Steps to reproduce:**
accessing skype and other microsoft services

**Comment by hectorm** [comment] 2024-07-25 14:22
I think it is a duplicate of hectorm/hblock#162, it should be fixed by now.

**Closed** 2024-07-25 14:24 UTC
Labels: bug
